// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "select_menu/internal/handler/auth"
	menu "select_menu/internal/handler/menu"
	"select_menu/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/api/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/random",
				Handler: menu.RandomHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get-by-name",
				Handler: menu.GetByNameHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get-by-material",
				Handler: menu.GetByMaterialHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/api/menu"),
	)
}
