info:
  contact: {}
paths:
  /login:
    post:
      parameters:
      - description: "13112345678"
        in: formData
        name: phone
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"code":200,"data":""}'
          schema:
            type: string
      summary: 用户登陆
      tags:
      - 公共方法
  /random:
    get:
      parameters:
      - description: hot_num
        in: query
        name: hot_num
        type: integer
      - description: cold_num
        in: query
        name: cold_num
        type: integer
      - description: soup_num
        in: query
        name: soup_num
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":""}'
          schema:
            type: string
      summary: 随机选择
      tags:
      - 公共方法
  /register:
    post:
      parameters:
      - description: name
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: phone
        in: formData
        name: phone
        required: true
        type: string
      - description: email
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{"code":200,"data":""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
swagger: "2.0"
